version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "${FRONTEND_URL}"
      BACKEND_URL: "${BACKEND_URL}"
    build: ./backend-flask
    network_mode: host
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL}"
      WDS_SOCKET_PORT: "0"
    build: ./frontend-react-js
    network_mode: host
    volumes:
      - ./frontend-react-js:/frontend-react-js

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks: 
  internal-network:
    driver: bridge
    name: cruddur